In [123]:
import pandas as pd
import csv
import csv as reader

In [124]:
bb = pd.read_csv('C:/Users/Leann Francisco/CODES/DW_3CSD/BigBasket Products.csv')
bb.head()

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [125]:
bb.tail()

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [126]:
bb.describe()

             index    sale_price  market_price        rating
count  27555.00000  27555.000000  27555.000000  18929.000000
mean   13778.00000    322.514808    382.056664      3.943410
std     7954.58767    486.263116    581.730717      0.739063
min        1.00000      2.450000      3.000000      1.000000
25%     6889.50000     95.000000    100.000000      3.700000
50%    13778.00000    190.000000    220.000000      4.100000
75%    20666.50000    359.000000    425.000000      4.300000
max    27555.00000  12500.000000  12500.000000      5.000000

In [127]:
# Check for null values
bb.isnull().sum()

index              0
product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [128]:
# setting the index column as index of the dataset
bb.set_index('index',inplace=True)
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [129]:
# Display rows with missing values along with the columns that are missing
missing_values = bb[bb.isnull().any(axis=1)]
missing_values[missing_values.isnull().any(axis=1)]
missing_values

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
56,Soothing Cucumber Facial Scrub With Apricot Seeds,Beauty & Hygiene,Skin Care,TJORI,299.4,499.0,Face Care,NaN,The soothing feel of cucumber meets the gentle...
60,Corporate Planner Diary With Premium PU Leathe...,Cleaning & Household,Stationery,Prozo Plus,399.0,399.0,"Notebooks, Files, Folders",NaN,A5 Size (210x150mm) \n192 Pages Premium Natura...
66,Ayurvedic Anti-Tan Face Pack,Beauty & Hygiene,Skin Care,TJORI,269.4,449.0,Face Care,NaN,A nourishing face pack that removes tan and br...
69,Organic Carom Seeds/Ajwain/Om Kalu,"Foodgrains, Oil & Masala",Masalas & Spices,Earthon,72.0,72.0,Whole Spices,NaN,"Earthon's Ajwain is Best quality, organically ..."
70,"Padded Harness - 3/4 inch, Grey Colour","Kitchen, Garden & Pets",Pet Food & Accessories,Glenand,840.0,840.0,Pet Collars & Leashes,NaN,These are soft padded harness for your active ...
...,...,...,...,...,...,...,...,...,...
27510,Deluxe Crackers - Veg,Gourmet & World Food,Chocolates & Biscuits,Kerk,150.0,150.0,"Cookies, Biscotti, Wafer",NaN,Kerk Biscuits-has been a household name synony...
27512,Specialist Stain Remover Pen & Marker,Cleaning & Household,All Purpose Cleaners,365,449.0,449.0,Imported Cleaners,NaN,Mightier than the pen. The pen may be mightier...
27515,Verge & Sheer Perfume For Pair,Beauty & Hygiene,Fragrances & Deos,Skinn by Titan,1615.5,1795.0,Perfume,NaN,VERGE for men paints a picture of a classy out...
27531,Tick'et to Fleadom Dry Shampoo For Dogs,"Kitchen, Garden & Pets",Pet Food & Accessories,Captain Zack,99.0,99.0,Pet Cleaning & Grooming,NaN,1) No Rinse Defence Against Ticks and Fleas: C...
27532,Vanilla Ice Cream,Gourmet & World Food,Dairy & Cheese,Haagen-Dazs,225.0,225.0,Gourmet Ice Cream,NaN,Some things are so good in their simplest form...

In [130]:
missing_values.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27510,Deluxe Crackers - Veg,Gourmet & World Food,Chocolates & Biscuits,Kerk,150.0,150.0,"Cookies, Biscotti, Wafer",NaN,Kerk Biscuits-has been a household name synony...
27512,Specialist Stain Remover Pen & Marker,Cleaning & Household,All Purpose Cleaners,365,449.0,449.0,Imported Cleaners,NaN,Mightier than the pen. The pen may be mightier...
27515,Verge & Sheer Perfume For Pair,Beauty & Hygiene,Fragrances & Deos,Skinn by Titan,1615.5,1795.0,Perfume,NaN,VERGE for men paints a picture of a classy out...
27531,Tick'et to Fleadom Dry Shampoo For Dogs,"Kitchen, Garden & Pets",Pet Food & Accessories,Captain Zack,99.0,99.0,Pet Cleaning & Grooming,NaN,1) No Rinse Defence Against Ticks and Fleas: C...
27532,Vanilla Ice Cream,Gourmet & World Food,Dairy & Cheese,Haagen-Dazs,225.0,225.0,Gourmet Ice Cream,NaN,Some things are so good in their simplest form...

In [131]:
# Check for columns with missing values
missing_columns = bb.columns[bb.isnull().any()]
print("Columns with missing values:", missing_columns)

Columns with missing values: Index(['product', 'brand', 'rating', 'description'], dtype='object')

In [132]:
# Fill missing values for 'rating' with the mean of the column
bb['rating'] = bb['rating'].fillna(bb['rating'].mean())

In [133]:
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [134]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [135]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [136]:
# Display rows with missing values along with the columns that are missing
missing_values = bb[bb.isnull().any(axis=1)]
missing_values[missing_values.isnull().any(axis=1)]
missing_values.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
289,Arrabbiata Tomato Pasta Sauce With Chilli,Gourmet & World Food,"Sauces, Spreads & Dips",Montanini,325.00,325.0,Mustard & Cheese Sauces,5.0,NaN
481,"Pumice Stone & Emery Foot Filer - FFL3407, Col...",Beauty & Hygiene,Bath & Hand Wash,Kaiv,175.00,175.0,Bathing Accessories,3.8,NaN
781,Peanut Butter - Chunky,Gourmet & World Food,"Sauces, Spreads & Dips",American Garden,299.00,299.0,"Chocolate, Peanut Spread",4.1,NaN
846,Squash - Sarasaparilla/Nannari/Sugandhi Root,Beverages,Fruit Juices & Drinks,NaturoBell,140.00,140.0,Syrups & Concentrates,2.5,NaN
1048,"Natura Rice & Walnut Drink, Vegan",Gourmet & World Food,Drinks & Beverages,BORGES,275.01,349.0,Health Drinks,4.5,NaN

In [137]:
# Check for columns with missing values
missing_columns = bb.columns[bb.isnull().any()]
print("Columns with missing values:", missing_columns)

Columns with missing values: Index(['product', 'brand', 'description'], dtype='object')

In [138]:
# Convert categorical columns to object
bb['product'] = bb['product'].fillna('Unknown')
bb['brand'] = bb['brand'].fillna('Unknown')
bb['description'] = bb['description'].fillna('No description available')
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [139]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [140]:
# Check for columns with missing values
missing_columns = bb.columns[bb.isnull().any()]
print("Columns with missing values:", missing_columns)

Columns with missing values: Index([], dtype='object')

In [141]:
# Display rows with missing values along with the columns that are missing
missing_values = bb[bb.isnull().any(axis=1)]
missing_values[missing_values.isnull().any(axis=1)]
missing_values

Empty DataFrame
Columns: [product, category, sub_category, brand, sale_price, market_price, type, rating, description]
Index: []

In [142]:
# Check for null values
bb.isnull().sum()

product         0
category        0
sub_category    0
brand           0
sale_price      0
market_price    0
type            0
rating          0
description     0
dtype: int64

In [143]:
# Standardize case
categorical_columns = bb.select_dtypes(include=['object']).columns
bb[categorical_columns] = bb[categorical_columns].apply(lambda x: x.str.lower())
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ..."
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.0,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m..."
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.0,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...

In [144]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori..."
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...

In [145]:
# Strip whitespace - Remove leading and trailing whitespaces in text fields.
bb[categorical_columns] = bb[categorical_columns].apply(lambda x: x.str.strip())
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ..."
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.0,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m..."
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.0,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...

In [146]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori..."
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...

In [147]:
# Data Type Conversion
bb.dtypes

product          object
category         object
sub_category     object
brand            object
sale_price      float64
market_price    float64
type             object
rating          float64
description      object
dtype: object

In [148]:
bb['product'] = bb['product'].astype('object')
bb['category'] = bb['category'].astype('category')
bb['sub_category'] = bb['sub_category'].astype('category')
bb['brand'] = bb['brand'].astype('category')
bb['type'] = bb['type'].astype('category')
bb['sale_price'] = bb['sale_price'].astype(float)
bb['market_price'] = bb['market_price'].astype(float)
bb['rating'] = bb['rating'].astype(float)
bb['description'] = bb['description'].astype(str)

In [149]:
bb.dtypes

product           object
category        category
sub_category    category
brand           category
sale_price       float64
market_price     float64
type            category
rating           float64
description       object
dtype: object

In [150]:
# Remove duplicates
bb.drop_duplicates()
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ..."
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.0,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m..."
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.0,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...

In [151]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
index,,,,,,,,,
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori..."
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...

In [152]:
# Validation: Flag rows where sale_price >= market_price
bb['invalid_price'] = bb['sale_price'] >= bb['market_price']
invalid_rows = bb[bb['invalid_price'] == True]

In [153]:
invalid_rows.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price
index,,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...,True
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ...",True
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...,True
7,multani mati,beauty & hygiene,skin care,satinance,58.0,58.0,face care,3.6,satinance multani matti is an excellent skin t...,True
8,hand sanitizer - 70% alcohol base,beauty & hygiene,bath & hand wash,bionova,250.0,250.0,hand wash & sanitizers,4.0,70%alcohol based is gentle of hand leaves skin...,True

In [154]:
invalid_rows.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price
index,,,,,,,,,,
27542,herbal rose & apricot walnut facial scrub,beauty & hygiene,skin care,khadi natural,250.0,250.0,face care,4.4,rose and apricot walnut face scrub helps in re...,True
27548,powder - baking,snacks & branded foods,ready to cook & eat,kwality,38.0,38.0,home baking,3.7,kwality baking powder directions for use: use ...,True
27549,apple cider vinegar shampoo,beauty & hygiene,hair care,morpheme remedies,499.0,499.0,shampoo & conditioner,5.0,"say no to dull, lifeless, dry and damaged hair...",True
27550,papad - garlic disco,snacks & branded foods,ready to cook & eat,atish,61.0,61.0,"papads, ready to fry",4.0,papads are prepared from urad dal flour and sp...,True
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.0,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...,True

In [155]:
bb

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price
index,,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.00,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...,True
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.00,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ...",True
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.00,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m...",False
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.00,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...,False
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.00,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...,True
...,...,...,...,...,...,...,...,...,...,...
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...,False
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...,False
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...,True
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori...",False
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...,False

In [156]:
# Discount/Price Difference
bb['market_price'] = pd.to_numeric(bb['market_price'], errors='coerce')
bb['sale_price'] = pd.to_numeric(bb['sale_price'], errors='coerce')

bb['price_difference'] = bb['market_price'] - bb['sale_price']
bb['price_difference'] = bb['price_difference'].apply(lambda x: f"{x:.2f}" if pd.notnull(x) else "")

In [157]:
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price,price_difference
index,,,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...,True,0.00
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ...",True,0.00
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.0,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m...",False,131.00
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.0,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...,False,27.00
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...,True,0.00

In [158]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price,price_difference
index,,,,,,,,,,,
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...,False,49.80
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...,False,7.50
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...,True,0.00
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori...",False,99.00
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...,False,175.47

In [159]:
# Price Range Category
def price_category(price):
    if price < 100:
        return 'Low'
    elif 100 <= price < 500:
        return 'Medium'
    else:
        return 'High'

bb['price_category'] = bb['sale_price'].apply(price_category)
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price,price_difference,price_category
index,,,,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...,True,0.00,Medium
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ...",True,0.00,Medium
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.0,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m...",False,131.00,Medium
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.0,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...,False,27.00,Medium
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...,True,0.00,Medium

In [160]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price,price_difference,price_category
index,,,,,,,,,,,,
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...,False,49.80,Medium
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...,False,7.50,Low
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...,True,0.00,Medium
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori...",False,99.00,Medium
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...,False,175.47,Medium

In [161]:
# Demand Category based on Rating
def demand_category(rating):
    if rating >= 4.5:
        return 'High Demand'
    elif rating >= 3.0:
        return 'Medium Demand'
    else:
        return 'Low Demand'

bb['demand_tier'] = bb['rating'].apply(demand_category)
bb.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price,price_difference,price_category,demand_tier
index,,,,,,,,,,,,,
1,garlic oil - vegetarian capsule 500 mg,beauty & hygiene,hair care,sri sri ayurveda,220.0,220.0,hair oil & serum,4.1,this product contains garlic oil that is known...,True,0.00,Medium,Medium Demand
2,water bottle - orange,"kitchen, garden & pets",storage & accessories,mastercook,180.0,180.0,water & fridge bottles,2.3,"each product is microwave safe (without lid), ...",True,0.00,Medium,Low Demand
3,"brass angle deep - plain, no.2",cleaning & household,pooja needs,trm,119.0,250.0,lamp & lamp oil,3.4,"a perfect gift for all occasions, be it your m...",False,131.00,Medium,Medium Demand
4,cereal flip lid container/storage jar - assort...,cleaning & household,bins & bathroom ware,nakoda,149.0,176.0,"laundry, storage baskets",3.7,multipurpose container with an attractive desi...,False,27.00,Medium,Medium Demand
5,creme soft soap - for hands & body,beauty & hygiene,bath & hand wash,nivea,162.0,162.0,bathing bars & soaps,4.4,nivea creme soft soap gives your skin the best...,True,0.00,Medium,Medium Demand

In [162]:
bb.tail()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description,invalid_price,price_difference,price_category,demand_tier
index,,,,,,,,,,,,,
27551,"wottagirl! perfume spray - heaven, classic",beauty & hygiene,fragrances & deos,layerr,199.20,249.0,perfume,3.9,layerr brings you wottagirl classic fragrant b...,False,49.80,Medium,Medium Demand
27552,rosemary,gourmet & world food,cooking & baking needs,puramate,67.50,75.0,"herbs, seasonings & rubs",4.0,puramate rosemary is enough to transform a dis...,False,7.50,Low,Medium Demand
27553,peri-peri sweet potato chips,gourmet & world food,"snacks, dry fruits, nuts",fabbox,200.00,200.0,nachos & chips,3.8,we have taken the richness of sweet potatoes (...,True,0.00,Medium,Medium Demand
27554,green tea - pure original,beverages,tea,tetley,396.00,495.0,tea bags,4.2,"tetley green tea with its refreshing pure, ori...",False,99.00,Medium,Medium Demand
27555,united dreams go far deodorant,beauty & hygiene,men's grooming,united colors of benetton,214.53,390.0,men's deodorants,4.5,the new mens fragrance from the united dreams ...,False,175.47,Medium,High Demand

In [163]:
bb.to_csv('bigbasket_transformed.csv', index=False)

In [164]:
import sqlite3 as sql1
import numpy as np

In [165]:
conn1 = sql1.connect('C:/Users/Karyle/Documents/3RD YEAR - 1st Semester/CS ELEC 1C - Data Warehousing/DW_3CSD/BIG_BASKET.db')

OperationalError: unable to open database file

In [ ]:
c1 = conn1.cursor()

In [ ]:
conn1.commit()

In [ ]:
bb = pd.read_sql('SELECT * FROM bigbasket_transformed', conn1)
bb.head()

In [ ]:
bb.tail()

In [ ]:
# Insights and Findings
# Product Category Distribution
import matplotlib.pyplot as plt
category_counts = bb['category'].value_counts()
category_counts.plot(kind='bar', figsize=(10, 6), color='pink')
plt.title('Product Category Distribution')
plt.xlabel('Categories')
plt.ylabel('Number of Products')
plt.show()

In [ ]:
# Top 10 Bestselling Products by Sale Price
top_bestselling = bb.sort_values(by='sale_price', ascending=False).head(10)
top_bestselling.plot(kind='barh', x='product', y='sale_price', figsize=(10, 6), color='pink')
plt.title('Top 10 Bestselling Products by Sale Price')
plt.xlabel('Sale Price')
plt.ylabel('Product Name')
plt.show()

In [ ]:
# Price Comparison Between Market Price and Sale Price
plt.figure(figsize=(8, 6))
plt.scatter(bb['market_price'], bb['sale_price'], alpha=0.5, color='pink')
plt.title('Price Comparison Between Market Price and Sale Price')
plt.xlabel('Market Price')
plt.ylabel('Sale Price')
plt.show()

In [ ]:
# Product Rating Distribution
plt.figure(figsize=(8, 6))
plt.hist(bb['rating'], bins=10, color='pink', edgecolor='black')
plt.title('Product Rating Distribution')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

In [ ]:
# Most Popular Brands
brand_counts = bb['brand'].value_counts().head(10)
brand_counts.plot(kind='pie', figsize=(8, 8), autopct='%1.1f%%', colors=plt.cm.Paired.colors)
plt.title('Most Popular Brands')
plt.ylabel('')
plt.show()

In [ ]:
# Sales and Rating Correlation
plt.figure(figsize=(8, 6))
plt.scatter(bb['sale_price'], bb['rating'], alpha=0.5, color='pink')
plt.title('Sales Price vs Rating Correlation')
plt.xlabel('Sale Price')
plt.ylabel('Rating')
plt.show()

In [ ]:
import seaborn as sns

In [ ]:
data = bb.category.value_counts()
sns.barplot(x=data,y=data.index, color='pink')
plt.xlabel('Count')
plt.ylabel('Categories')
plt.title('Top Selling Categories')

In [ ]:
bb.shape

In [ ]:
import plotly.express as px

In [ ]:
counts = bb['brand'].value_counts()

counts_bb_brand = pd.DataFrame({'Brand Name':counts.index,'Counts':counts.values})[:10]
px.bar(data_frame=counts_bb_brand,
 x='Brand Name',
 y='Counts',
 color='Counts',
 color_continuous_scale='blues',
 text_auto=True,
 title=f'Top 10 Brand Items based on Item Counts')

In [ ]:
# Category Revenue
data = bb.sale_price.groupby(bb.category).sum()
plt.figure(figsize=(6, 6)) 
plt.pie(x=data, 
        labels=data.index, 
        startangle=90, 
        autopct='%1.1f%%', 
        colors=plt.cm.Paired.colors) 
plt.title('How each Category Contributes to Total Revenue')
plt.ylabel('') 
plt.show()

In [ ]:
# Handle missing values
# categorical_columns = bb.select_dtypes(include=['object']).columns
#for col in categorical_columns:
 #   bb[col] = bb[col].fillna(bb[col].mode()[0])
#bb